### ISSUE TITLE
Create `ssl_context` only once

### ISSUE THREAD

**Issue by vog** [m-click/requests_pkcs12#2]
The `ssl_context` should be created only once, instead of storing the PKCS#12 password in memory for the whole lifetime of the adapter.

**Comment by rashley-iqt** [comment]
I think i have a fix for this in place.  Do you have any sort of standard test you run through?

**Comment by vog** [comment]
That's great!

Regarding testing, just file a pull request, and I'll review and test this before merging.

**Comment by vog** [comment]
If everything is fine, a new release will follow, of course.

**Comment by vog** [comment]
Thanks!
