### ISSUE TITLE
Library does not work correctly with  transfer-encoding: chunked

### ISSUE THREAD

**Issue by DiegoEPaez** [m-click/requests_pkcs12#25]
Although the library is working correctly with p12 files when receiving headers and the first chunk of a response with no content-length but transfer-chunked enabled, it has a problem when attempting to receive the next chunks, it throws an exception of IncompleteRead when in fact it should be reading the next chunk.

It is not a problem of the server side because I am getting the correct information using Java. Specifically, I used HttpURLConnection Java class and it works fine (plus setting the parameters  -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStore=... -Djavax.net.ssl.keyStorePassword=...). It also works fine with Java class HttpClient.

**Comment by DiegoEPaez** [comment]
Additionaly, I am getting an ('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')")) error.

**Comment by vog** [comment]
This sound more like an issue with the requests library.

Do you have a setup where you can try it again without needing a PKCS#12 certificate, so you can use the requests library directly rather than requests_pkcs12?

Then we would have a direct comparison showing which library triggers the bug.

**Comment by DiegoEPaez** [comment]
Thanks for the answer Volker. Unfortunately I cannot run the experiment you suggest since I do not control the server hosting the site. I will try to debug the problem. Any further suggestions will be appreciated.

**Comment by DiegoEPaez** [comment]
Update: I tried debugging the problem, so far I have followed the execution thread until _safe_read(self, amt) of http.client.HTTPResponse. Within that method it breaks when it tries to execute:

self.fp.read(min(amt, MAXAMOUNT))

but I am unsure why, what happens is that when the request is sent (in the send method of the request.Session object) it uses the Pkcs12Adapter (and therefore the HTTPAdapter), to send the request, and then a response is given with the headers, but no chunks of the body.

So far everything is good. The thing is then that the HTTPAdapter returns a Response object (requests.models.Response) in its send method, and here is the problem, because later on we will be needing to get the body but we will no longer be using the adapter, but rather this Response object.

When the contents of the body are requested (near the end of the send method in request.Session), it uses this standard HTTPResponse object to do the chunking process, but fails.

I am unsure how to proceed to debug this thing. The self.fp.read method seems to be a compiled method, and so I don't know how to follow what is happening, any help would be appreciated. Additionally, this may look like it is a bug with the requests library when using chunking + SSL certificates but I am unsure, I would also appreciate any confirmation on this.

**Comment by vog** [comment]
From your description it is pretty sure that this has nothing to to with `requests_pkcs12`.

Please convert you pkcs12 certificate to a PEM certificate and try to reproduce this issue using the plain `requests` library.

Then, open a bug at the `requests` issue tracker:

* https://github.com/psf/requests/issues

**Comment by DiegoEPaez** [comment]
Thanks Volker, I will try that.
