### ISSUE TITLE
Adding headers to the call

### ISSUE THREAD

**Issue by mkane848** [m-click/requests_pkcs12#3]
Hey @vog, just got around to checking your solution out from that main issue thread. Quick question: is there a way to pass header information along with the request call? I'm poking around the code a little bit but don't see it, but I'm also not super familiar with requests so I'm reading their docs concurrently.

I tried adding headers to the __init__ function and updating the session's header info in the request function but keep getting a 405 error when I call it.

Thanks,
Mike

**Comment by vog** [comment]
The functions provided by `requests_pkcs12` accept all parameters of `requests`, by simpling forwarding all unhandled options to `requests`.

So it should just work. You don't need to change anything in `requests_pkcs12`.

If your code doesn't work, please provide a minimal program that reproduces the issue.

**Comment by vog** [comment]
I assume this issue is solved. Feel free to re-open this issue if you want to provide a minimal program that reproduces the issue.
