### ISSUE TITLE
create_ssl_sslcontext raises `TypeError: Encryption algorithm must be a KeySerializationEncryption instance`

### ISSUE THREAD

**Issue by MWMWM** [m-click/requests_pkcs12#32]
I get `TypeError: Encryption algorithm must be a KeySerializationEncryption instance` when invoking `create_ssl_sslcontext` function

After changing https://github.com/m-click/requests_pkcs12/blob/master/requests_pkcs12.py#L69 to
`cryptography.hazmat.primitives.serialization.BestAvailableEncryption(password=pkcs12_password_bytes)`
everything is working fine

**Comment by vog** [comment]
Thanks for reporting! Would you mind creating a Pull Request for your proposed fix?

**Comment by MWMWM** [comment]
@vog Pull Request is awaiting - will you be able to take a look?

**Comment by vog** [comment]
@MWMWM Thanks for the reminder and sorry for the delay!

The pull request is fine and I just released a new version **1.14** of `requests_pkcs12`:

* https://pypi.org/project/requests-pkcs12/
