### ISSUE TITLE
OpenSSL.SSL.Error: [('SSL routines', '', 'ca md too weak')]

### ISSUE THREAD

**Issue by KyleGobel** [m-click/requests_pkcs12#34]
On a machine I'm running it has OpenSSL 3.x, the CA I'm using cannot be changed and is stuck using sha1.

Is there a way from code with this library to set it/open ssl to allow this now considered 'weak' hashing ?

I've been trying to guess and check with things like the following -- but no change in behavior

```
requests_pkcs12.urllib3.contrib.pyopenssl.DEFAULT_SSL_CIPHER_LIST = 'ALL:@SECLEVEL=0'
requests_pkcs12.urllib3.contrib.pyopenssl.util.ssl_.DEFAULT_CIPHERS = 'ALL:@SECLEVEL=0'
requests_pkcs12.OpenSSL.crypto.DEFAULT_CIPHER = 'ALL:@SECLEVEL=0'
```

**Comment by vog** [comment]
Please repeat your question to the pyOpenSSL project. There is nothing the requests_pkcs12 project can do about this.
