### ISSUE TITLE
Using a retry strategy

### ISSUE THREAD

**Issue by domsie** [m-click/requests_pkcs12#35]
Hi,
is it possible using an Pkcs12Adapter and still using a retry-strategy like in the following post:

https://majornetwork.net/2022/04/handling-retries-in-python-requests/

```
from urllib3 import Retry
session = requests.Session()
adapter = HTTPAdapter(max_retries=Retry(total=4, backoff_factor=1, allowed_methods=None, status_forcelist=[429, 500, 502, 503, 504]))
```

**Background of my question:**
We detect many connection refused errors, when connecting from a specific client (flask app that using an Pkcs12Adapter), like:

```
Max retries exceeded with url: / (Caused by NewConnectionError(’<urllib3.connection.HTTPConnection object at 0x7f492268db20>: Failed to establish a new connection: [Errno 111] Connection refused’)
```

To resolve that problem i am wants to try out a retry-strategy.

**Comment by vog** [comment]
Yes, the Pkcs12Adapter is meant to be compatible with HTTPAdapter. Please give it a try, and if you encounter any issues along this road, please feel free to report those.
