### ISSUE TITLE
Cannot Set verify_mode to CERT_NONE when check_hostname is Enabled

### ISSUE THREAD

**Issue by kamranzafar** [m-click/requests_pkcs12#47]
_Latest version_ doesn't work with **verify=False**, getting the following error 

_Cannot Set verify_mode to CERT_NONE when check_hostname is Enabled_

Works fine on version 1.14

**Comment by vog** [comment]
Good catch! Are you able and willing to provide a pull request to fix this?

**Comment by yonting** [comment]
I do not know how to make a fix for this. You can change `ssl_protocol`, so `Pkcs12Adapter(..., ssl_protocol=ssl.PROTOCOL_SSLv23)`, maybe, but `ssl.PROTOCOL_SSLv23` is deprecated.

**Comment by yonting** [comment]
I have made a PR which I think is a fix for this.

**Comment by yonting** [comment]
I made a PR with a potential fix.

**Comment by vog** [comment]
Thanks a lot for your contribution! Although your solution is quite a hack, I don't see any better solution, either. I just released version 1.17 containing your fix:

https://pypi.org/project/requests-pkcs12/
