### ISSUE TITLE
linking closed, duplicate requests issue instead of open variant

### ISSUE THREAD

**Issue by medelhoff** [m-click/requests_pkcs12#49]
Hi,
just a quick observation:
`README.rst` is linking requests issue [1573](https://github.com/psf/requests/issues/1573) which has since been closed as duplicate of [2519](https://github.com/psf/requests/issues/2519). That issue is still open ans afaics there is no solution. 

anyway, I though  it silly to create a pull request :D

**Comment by vog** [comment]
Any PR is welcome, even for small changes.

**Comment by vog** [comment]
I updated the README.
