### ISSUE TITLE
Add example of two-way TLS/SSL configuration

### ISSUE THREAD

**Issue by AleksandarSavic95** [m-click/requests_pkcs12#5]
When I read the last line of the README.md file:

> If you use these parameters, don't use the built-in `cert` parameter of `requests` at the same time. 

I thought that the `verify` field shouldn't be used as well, which resulted in lots of attempts which didn't happen to work.
The only way I succeded in setting up two-way SSL was by puting the **root CA**'s certificate filename in the `verify` field (`rootCA.pem` in my case).

**Suggestion**: add a line below the quoted one saying something like this.

> This doesn't mean that You can't use the `verify` field, which *should* be used for two-way SSL. Check out the [requests library documentation for the `verify` field](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification).

P.S. Thank you for this small, but useful library! 🙂

**Comment by vog** [comment]
I just improved the README. Thanks for the suggestion!

**Comment by AleksandarSavic95** [comment]
Thank You for being a devoted coder! 😊 
Best of luck with further development! :)
