### ISSUE TITLE
`cryptography.x509.Certificate.not_valid_after` is deprecated

### ISSUE THREAD

**Issue by yonting** [m-click/requests_pkcs12#51]
`cryptography.x509.Certificate.not_valid_after` is [deprecated](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_after) since [version 42.0.0](https://cryptography.io/en/latest/changelog/#v42-0-0). It is used in library:

https://github.com/m-click/requests_pkcs12/blob/fe83fb58785f884fbe69e8466e9d66aae0069272/requests_pkcs12.py#L38

It can use [`cryptography.x509.Certificate.not_valid_after_utc`](https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_after_utc) instead but then need `cryptography>= 42.0.0` in `setup.py`.

What are you thinking?

I can do a PR.

**Comment by yonting** [comment]
Did a PR if you want the change.

**Comment by vog** [comment]
Thanks for your contribution. I accepted it as-is, but had to apply another fix to solve the following error:

    TypeError: can't compare offset-naive and offset-aware datetimes

(see above)

**Comment by vog** [comment]
I just released a new version requests-pkcs12 1.23 that contains your fix:

* https://pypi.org/project/requests-pkcs12/

Again, thanks for your contribution!
