### ISSUE TITLE
Problem with non-TLS-1.2 server

### ISSUE THREAD

**Issue by tobiasdirksen** [m-click/requests_pkcs12#7]
I'm trying to read the following:
`r = get("https://eloverblik.dk/api/authorizationsv2", pkcs12_filename="C:/PathToCertificate.p12", pkcs12_password="mypassword")`
however I get the result
`SSLError: HTTPSConnectionPool(host='eloverblik.dk', port=443): Max retries exceeded with url: /api/authorizationsv2 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],)",),))`
I'm able to open and read the certificate using `OpenSSL`, so the certificate is working. I can also read the url in Firefox.
I am using requests_pkcs12 version 1.0.5 and python 3.6.1. 
Any ideas what goes wrong?

**Comment by vog** [comment]
Just a wild guess: Maybe the server you are communicating with doesn't support TLS 1.2?

If that is the case, you could try a different constant in the `_create_ssl_context()` method:

```
 ssl_context = PyOpenSSLContext(PROTOCOL_TLSv1_2)
```

(Don't forget to adjust the `import` statement as well.)

**Comment by tobiasdirksen** [comment]
Thanks for writing back. The server supports TLS 1.3. I can't change it to `PyOpenSSLContext(PROTOCOL_TLSv1_3)` but that shouldn't be necessary I assume?

**Comment by vog** [comment]
It seems there is no "PROTOCOL_TLSv1_3" constant. Also, I must confess that I still don't fully understand the whole API mess with the Python modules "ssl", "PyOpenSSL", "requests" and those wrappers around wrappers between them.

I would love to simply create an `ssl_context` that is just configured to the best version that both client and server do support. But the constructor requires one of those constants as mandatory first argument, and there is no such constant like "TLS1_2_OR_BETTER".

**Comment by tobiasdirksen** [comment]
Ah okay, that seems to explains my problem. Thanks.

**Comment by vog** [comment]
Feel free to share your solution as soon as you have found one.

**Comment by tobiasdirksen** [comment]
Sure!

**Comment by vog** [comment]
I just released version 1.3 of `requests_pkcs12`, with some improvements in the usage of the `PROTOCOL_*` constants.

Thanks to @rashley-iqt for pointing me to the right direction in #9.

@tobiasdirksen Please check if 1.3 solves your problem.

**Comment by rashley-iqt** [comment]
As a side note here, I don't think you want to use `PROTOCOL_SSLv23` as a long term solution.  that alias has been deprecated in [2.7.13](https://docs.python.org/2.7/library/ssl.html#ssl.PROTOCOL_SSLv23) and [3.6](https://docs.python.org/3.7/library/ssl.html#ssl.PROTOCOL_SSLv23).  I think it would be better to try to import the `PROTOCOL_TLS` alias first and fall through to the `PROTOCOL_SSLv23` alias if it is not available.  I think that will give you the best combination of up to date functionality and backwards compatibility.

**Comment by vog** [comment]
Of course! And this has already been implemented in https://github.com/m-click/requests_pkcs12/commit/b51390056073fc88aad0386cc5bab7cb7a1faad5, so it is part of release 1.3

**Comment by rashley-iqt** [comment]
My apologies.  I misread the commit history.

**Comment by vog** [comment]
@tobiasdirksen Did you find some time to check if 1.3 solves your problem?

**Comment by vog** [comment]
@tobiasdirksen Does the latest version (meanwhile 1.6) work for you?

**Comment by tobiasdirksen** [comment]
Apologies for late feedback, but I have been on leave for a while. The latest version is indeed working. Thanks a lot for your help.

**Comment by vog** [comment]
Thanks for your feedback!

**Comment by deajan** [comment]
@tobiasdirksen Did you manage to get TLSv1.3 work with requests_pkcs12 or did you downgrade the protocol used ? Thanks.
